# Generated by Django 5.2.4 on 2025-08-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebsiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        help_text="Unique key for the setting",
                        max_length=255,
                        unique=True,
                        verbose_name="Key",
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="Value of the setting", verbose_name="Value"
                    ),
                ),
            ],
            options={
                "verbose_name": "Website Setting",
                "verbose_name_plural": "Website Settings",
            },
        ),
    ]
